use serde::{Deserialize, Serialize};

use crate::{
    nbt::tag::{BooleanTag, ByteTag, IntTag, ListTag, ShortTag, StringTag},
    schema::bedrock::block::Block,
};

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct Item {
    Block: Option<Block>,
    CanDestroy: Option<ListTag<StringTag<ItemResource>>>,
    CanPlaceOn: Option<ListTag<StringTag<ItemResource>>>,
    Count: ByteTag,
    Damage: ShortTag,
    Name: StringTag<ItemResource>,
    tag: Option<ItemTag>,
    WasPickedUp: BooleanTag, // approximated, not documented completely. optional? doesn't appear to be
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct ItemTag {
    Damage: Option<IntTag>,
    display: Option<ItemDisplayTag>,
    // ... needs to be completed
    // https://minecraft.wiki/w/Bedrock_Edition_level_format/Item_format
}

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize)]
pub struct ItemDisplayTag {
    Lore: Option<ListTag<StringTag>>,
    Name: Option<StringTag>,
}

// Needs to be prefixed with `minecraft:` when serialized
#[allow(non_camel_case_types)]
#[derive(Serialize, Deserialize)]
pub enum ItemResource {
    iron_shovel,
    iron_pickaxe,
    iron_axe,
    flint_and_steel,
    apple,
    bow,
    arrow,
    coal,
    diamond,
    iron_ingot,
    gold_ingot,
    iron_sword,
    wooden_sword,
    wooden_shovel,
    wooden_pickaxe,
    wooden_axe,
    stone_sword,
    stone_shovel,
    stone_pickaxe,
    stone_axe,
    diamond_sword,
    diamond_shovel,
    diamond_pickaxe,
    diamond_axe,
    stick,
    bowl,
    mushroom_stew,
    golden_sword,
    golden_shovel,
    golden_pickaxe,
    golden_axe,
    string,
    feather,
    gunpowder,
    wooden_hoe,
    stone_hoe,
    iron_hoe,
    diamond_hoe,
    golden_hoe,
    wheat_seeds,
    wheat,
    bread,
    leather_helmet,
    leather_chestplate,
    leather_leggings,
    leather_boots,
    chainmail_helmet,
    chainmail_chestplate,
    chainmail_leggings,
    chainmail_boots,
    iron_helmet,
    iron_chestplate,
    iron_leggings,
    iron_boots,
    diamond_helmet,
    diamond_chestplate,
    diamond_leggings,
    diamond_boots,
    golden_helmet,
    golden_chestplate,
    golden_leggings,
    golden_boots,
    flint,
    porkchop,
    cooked_porkchop,
    painting,
    golden_apple,
    oak_sign,
    wooden_door,
    bucket,
    minecart,
    saddle,
    iron_door,
    redstone,
    snowball,
    boat,
    leather,
    kelp,
    brick,
    clay_ball,
    sugar_cane,
    paper,
    book,
    slime_ball,
    chest_minecart,
    egg,
    compass,
    fishing_rod,
    clock,
    glowstone_dust,
    cod,
    cooked_cod,
    dye,
    bone,
    sugar,
    cake,
    bed,
    repeater,
    cookie,
    filled_map,
    shears,
    melon_slice,
    pumpkin_seeds,
    melon_seeds,
    beef,
    cooked_beef,
    chicken,
    cooked_chicken,
    rotten_flesh,
    ender_pearl,
    blaze_rod,
    ghast_tear,
    gold_nugget,
    nether_wart,
    potion,
    glass_bottle,
    spider_eye,
    fermented_spider_eye,
    blaze_powder,
    magma_cream,
    brewing_stand,
    cauldron,
    ender_eye,
    glistering_melon_slice,
    spawn_egg,
    experience_bottle,
    fire_charge,
    writable_book,
    written_book,
    emerald,
    frame,
    flower_pot,
    carrot,
    potato,
    baked_potato,
    poisonous_potato,
    empty_map,
    golden_carrot,
    skull,
    carrot_on_a_stick,
    nether_star,
    pumpkin_pie,
    firework_rocket,
    firework_star,
    enchanted_book,
    comparator,
    netherbrick,
    quartz,
    tnt_minecart,
    hopper_minecart,
    prismarine_shard,
    hopper,
    rabbit,
    cooked_rabbit,
    rabbit_stew,
    rabbit_foot,
    rabbit_hide,
    leather_horse_armor,
    iron_horse_armor,
    golden_horse_armor,
    diamond_horse_armor,
    lead,
    name_tag,
    prismarine_crystals,
    mutton,
    cooked_mutton,
    armor_stand,
    end_crystal,
    spruce_door,
    birch_door,
    jungle_door,
    acacia_door,
    dark_oak_door,
    chorus_fruit,
    popped_chorus_fruit,
    banner_pattern,
    dragon_breath,
    splash_potion,
    lingering_potion,
    sparkler,
    command_block_minecart,
    elytra,
    shulker_shell,
    banner,
    medicine,
    balloon,
    rapid_fertilizer,
    totem_of_undying,
    bleach,
    iron_nugget,
    ice_bomb,
    chalkboard,
    trident,
    portfolio,
    beetroot,
    beetroot_seeds,
    beetroot_soup,
    salmon,
    tropical_fish,
    pufferfish,
    cooked_salmon,
    dried_kelp,
    nautilus_shell,
    enchanted_golden_apple,
    heart_of_the_sea,
    scute,
    turtle_helmet,
    phantom_membrane,
    crossbow,
    spruce_sign,
    birch_sign,
    jungle_sign,
    acacia_sign,
    dark_oak_sign,
    sweet_berries,
    camera,
    compound,
    music_disc_13,
    music_disc_cat,
    music_disc_blocks,
    music_disc_chirp,
    music_disc_far,
    music_disc_mall,
    music_disc_mellohi,
    music_disc_stal,
    music_disc_strad,
    music_disc_ward,
    music_disc_11,
    music_disc_wait,
    shield,
    glow_ink_sac,
    raw_iron,
    raw_gold,
    raw_copper,
    campfire,
    suspicious_stew,
    honeycomb,
    honey_bottle,
    lodestone_compass,
    netherite_ingot,
    netherite_sword,
    netherite_shovel,
    netherite_pickaxe,
    netherite_axe,
    netherite_hoe,
    netherite_helmet,
    netherite_chestplate,
    netherite_leggings,
    netherite_boots,
    netherite_scrap,
    crimson_sign,
    warped_sign,
    crimson_door,
    warped_door,
    warped_fungus_on_a_stick,
    chain,
    music_disc_pigstep,
    nether_sprouts,
    goat_horn,
    amethyst_shard,
    spyglass,
    music_disc_otherside,
    soul_campfire,
    glow_frame,
}
