pub enum BlockResource {
    Air = 0,
    Stone,
    GrassBlock,
    Dirt,
    Cobblestone,
    Planks,
    Sapling,
    Bedrock,
    WaterFlowing,
    Water,
    LavaFlowing,
    Lava,
    Sand,
    Gravel,
    GoldOre,
    IronOre,
    CoalOre,
    Log,
    Leaves,
    Glass = 20,
    LapisOre,
    LapisBlock,
    Sandstone = 24,
    Bed = 26,
    Cobweb = 30,
    Bush,
    Wool = 35,
    Dandelion = 37,
    BlueRose,
    BrownMushroom,
    RedMushroom,
    GoldBlock,
    IronBlock,
    DoubleSlab,
    Slab,
    Bricks,
    Tnt,
    Bookshelf,
    MossyCobblestone,
    Obsidian,
    Torch,
    Fire,
    WoodenStairs = 53,
    Chest,
    DiamondOre = 56,
    DiamondBlock,
    CraftingTable,
    Wheat,
    Farmland,
    Furnace,
    LitFurnace,
    Sign,
    WoodenDoor,
    Ladder,
    CobblestoneStairs = 67,
    WallSign,
    IronDoor = 71,
    RedstoneOre = 73,
    LitRedstoneOre,
    Snow = 78,
    Ice,
    SnowBlock,
    Cactus,
    Clay,
    Sugarcane,
    Fence = 85,
    Netherrack = 87,
    Glowstone = 89,
    BedrockInvisible = 95,
    Trapdoor,
    StoneBricks = 98,
    GlassPane = 102,
    Melon,
    MelonStem = 105,
    FenceGate = 107,
    BrickStairs,
    StoneBrickStairs,
    NetherBricks = 112,
    NetherBrickStairs = 114,
    SandstoneStairs = 128,
    QuartzBlock = 155,
    QuartzStairs,
    Stonecutter = 245,
    LitObsidian,
    NetherReactorCore,
    Update,
    Ateupd,
    GrassBlockCarried = 253,
    LeavesCarried,
    Stone1,
}
