use crate::{
    convert::convert_to::ConvertTo,
    schema::{java::v1_20::item as java, pi::v0_1_1::item as pi},
};

impl ConvertTo<pi::Item> for java::Item {
    fn convert(&self) -> pi::Item {
        pi::Item {
            id: self.id.convert(),
            Damage: self.tag.as_ref().map_or(0, |tag| clamp_damage(tag.Damage)),
            Count: self.Count,
        }
    }
}

/// Converts a Java Edition item damage value (`i32`) to a Bedrock Edition-compatible value (`i16`).
///
/// In Java Edition, `Damage` is stored as a 32-bit signed integer. In Bedrock Edition,
/// it is stored as a 16-bit signed integer. To preserve vanilla-compatible behavior,
/// this function clamps the input to the valid `i16` range: -32,768 to 32,767.
///
/// This avoids overflow and wraparound artifacts that could result in undefined behavior
/// or corrupted item states in Bedrock.
///
/// # Parameters
/// - `value`: The Java Edition `Damage` value as `i32`.
///
/// # Returns
/// A clamped `i16` value safe for use in Bedrock Edition NBT.
///
/// # Example
/// ```
/// let bedrock_damage = clamp_damage(40000);
/// assert_eq!(bedrock_damage, 32767);
/// ```
fn clamp_damage(value: i32) -> i16 {
    value.clamp(i16::MIN as i32, i16::MAX as i32) as i16
}

impl ConvertTo<pi::ItemResource> for java::ItemResource {
    fn convert(&self) -> pi::ItemResource {
        match self {
            Self::acacia_boat => pi::ItemResource::acacia_boat,
            Self::amethyst_shard => pi::ItemResource::amethyst_shard,
            Self::apple => pi::ItemResource::apple,
            Self::armor_stand => pi::ItemResource::armor_stand,
            Self::arrow => pi::ItemResource::arrow,
            Self::axolotl_bucket => pi::ItemResource::axolotl_bucket,
            Self::axolotl_spawn_egg => pi::ItemResource::axolotl_spawn_egg,
            Self::baked_potato => pi::ItemResource::baked_potato,
            Self::bat_spawn_egg => pi::ItemResource::bat_spawn_egg,
            Self::bee_spawn_egg => pi::ItemResource::bee_spawn_egg,
            Self::beef => pi::ItemResource::beef,
            Self::beetroot => pi::ItemResource::beetroot,
            Self::beetroot_seeds => pi::ItemResource::beetroot_seeds,
            Self::beetroot_soup => pi::ItemResource::beetroot_soup,
            Self::birch_boat => pi::ItemResource::birch_boat,
            Self::black_dye => pi::ItemResource::black_dye,
            Self::blaze_powder => pi::ItemResource::blaze_powder,
            Self::blaze_rod => pi::ItemResource::blaze_rod,
            Self::blaze_spawn_egg => pi::ItemResource::blaze_spawn_egg,
            Self::blue_dye => pi::ItemResource::blue_dye,
            Self::bone => pi::ItemResource::bone,
            Self::bone_meal => pi::ItemResource::bone_meal,
            Self::book => pi::ItemResource::book,
            Self::bow => pi::ItemResource::bow,
            Self::bowl => pi::ItemResource::bowl,
            Self::bread => pi::ItemResource::bread,
            Self::brick => pi::ItemResource::brick,
            Self::brown_dye => pi::ItemResource::brown_dye,
            Self::bucket => pi::ItemResource::bucket,
            Self::bundle => pi::ItemResource::bundle,
            Self::carrot => pi::ItemResource::carrot,
            Self::carrot_on_a_stick => pi::ItemResource::carrot_on_a_stick,
            Self::cat_spawn_egg => pi::ItemResource::cat_spawn_egg,
            Self::cave_spider_spawn_egg => pi::ItemResource::cave_spider_spawn_egg,
            Self::chainmail_boots => pi::ItemResource::chainmail_boots,
            Self::chainmail_chestplate => pi::ItemResource::chainmail_chestplate,
            Self::chainmail_helmet => pi::ItemResource::chainmail_helmet,
            Self::chainmail_leggings => pi::ItemResource::chainmail_leggings,
            Self::charcoal => pi::ItemResource::charcoal,
            Self::chest_minecart => pi::ItemResource::chest_minecart,
            Self::chicken => pi::ItemResource::chicken,
            Self::chicken_spawn_egg => pi::ItemResource::chicken_spawn_egg,
            Self::chorus_fruit => pi::ItemResource::chorus_fruit,
            Self::clay_ball => pi::ItemResource::clay_ball,
            Self::clock => pi::ItemResource::clock,
            Self::coal => pi::ItemResource::coal,
            Self::cocoa_beans => pi::ItemResource::cocoa_beans,
            Self::cod => pi::ItemResource::cod,
            Self::cod_bucket => pi::ItemResource::cod_bucket,
            Self::cod_spawn_egg => pi::ItemResource::cod_spawn_egg,
            Self::command_block_minecart => pi::ItemResource::command_block_minecart,
            Self::compass => pi::ItemResource::compass,
            Self::cooked_beef => pi::ItemResource::cooked_beef,
            Self::cooked_chicken => pi::ItemResource::cooked_chicken,
            Self::cooked_cod => pi::ItemResource::cooked_cod,
            Self::cooked_mutton => pi::ItemResource::cooked_mutton,
            Self::cooked_porkchop => pi::ItemResource::cooked_porkchop,
            Self::cooked_rabbit => pi::ItemResource::cooked_rabbit,
            Self::cooked_salmon => pi::ItemResource::cooked_salmon,
            Self::cookie => pi::ItemResource::cookie,
            Self::copper_ingot => pi::ItemResource::copper_ingot,
            Self::cow_spawn_egg => pi::ItemResource::cow_spawn_egg,
            Self::creeper_banner_pattern => pi::ItemResource::creeper_banner_pattern,
            Self::creeper_spawn_egg => pi::ItemResource::creeper_spawn_egg,
            Self::crossbow => pi::ItemResource::crossbow,
            Self::cyan_dye => pi::ItemResource::cyan_dye,
            Self::dark_oak_boat => pi::ItemResource::dark_oak_boat,
            Self::debug_stick => pi::ItemResource::debug_stick,
            Self::diamond => pi::ItemResource::diamond,
            Self::diamond_axe => pi::ItemResource::diamond_axe,
            Self::diamond_boots => pi::ItemResource::diamond_boots,
            Self::diamond_chestplate => pi::ItemResource::diamond_chestplate,
            Self::diamond_helmet => pi::ItemResource::diamond_helmet,
            Self::diamond_hoe => pi::ItemResource::diamond_hoe,
            Self::diamond_horse_armor => pi::ItemResource::diamond_horse_armor,
            Self::diamond_leggings => pi::ItemResource::diamond_leggings,
            Self::diamond_pickaxe => pi::ItemResource::diamond_pickaxe,
            Self::diamond_shovel => pi::ItemResource::diamond_shovel,
            Self::diamond_sword => pi::ItemResource::diamond_sword,
            Self::dolphin_spawn_egg => pi::ItemResource::dolphin_spawn_egg,
            Self::donkey_spawn_egg => pi::ItemResource::donkey_spawn_egg,
            Self::dragon_breath => pi::ItemResource::dragon_breath,
            Self::dried_kelp => pi::ItemResource::dried_kelp,
            Self::drowned_spawn_egg => pi::ItemResource::drowned_spawn_egg,
            Self::egg => pi::ItemResource::egg,
            Self::elder_guardian_spawn_egg => pi::ItemResource::elder_guardian_spawn_egg,
            Self::elytra => pi::ItemResource::elytra,
            Self::emerald => pi::ItemResource::emerald,
            Self::enchanted_book => pi::ItemResource::enchanted_book,
            Self::enchanted_golden_apple => pi::ItemResource::enchanted_golden_apple,
            Self::end_crystal => pi::ItemResource::end_crystal,
            Self::ender_eye => pi::ItemResource::ender_eye,
            Self::ender_pearl => pi::ItemResource::ender_pearl,
            Self::enderman_spawn_egg => pi::ItemResource::enderman_spawn_egg,
            Self::endermite_spawn_egg => pi::ItemResource::endermite_spawn_egg,
            Self::evoker_spawn_egg => pi::ItemResource::evoker_spawn_egg,
            Self::experience_bottle => pi::ItemResource::experience_bottle,
            Self::feather => pi::ItemResource::feather,
            Self::fermented_spider_eye => pi::ItemResource::fermented_spider_eye,
            Self::filled_map => pi::ItemResource::filled_map,
            Self::fire_charge => pi::ItemResource::fire_charge,
            Self::firework_rocket => pi::ItemResource::firework_rocket,
            Self::firework_star => pi::ItemResource::firework_star,
            Self::fishing_rod => pi::ItemResource::fishing_rod,
            Self::flint => pi::ItemResource::flint,
            Self::flint_and_steel => pi::ItemResource::flint_and_steel,
            Self::flower_banner_pattern => pi::ItemResource::flower_banner_pattern,
            Self::fox_spawn_egg => pi::ItemResource::fox_spawn_egg,
            Self::furnace_minecart => pi::ItemResource::furnace_minecart,
            Self::ghast_spawn_egg => pi::ItemResource::ghast_spawn_egg,
            Self::ghast_tear => pi::ItemResource::ghast_tear,
            Self::glass_bottle => pi::ItemResource::glass_bottle,
            Self::glistering_melon_slice => pi::ItemResource::glistering_melon_slice,
            Self::globe_banner_pattern => pi::ItemResource::globe_banner_pattern,
            Self::glow_berries => pi::ItemResource::glow_berries,
            Self::glow_ink_sac => pi::ItemResource::glow_ink_sac,
            Self::glow_item_frame => pi::ItemResource::glow_item_frame,
            Self::glow_squid_spawn_egg => pi::ItemResource::glow_squid_spawn_egg,
            Self::glowstone_dust => pi::ItemResource::glowstone_dust,
            Self::goat_spawn_egg => pi::ItemResource::goat_spawn_egg,
            Self::gold_ingot => pi::ItemResource::gold_ingot,
            Self::gold_nugget => pi::ItemResource::gold_nugget,
            Self::golden_apple => pi::ItemResource::golden_apple,
            Self::golden_axe => pi::ItemResource::golden_axe,
            Self::golden_boots => pi::ItemResource::golden_boots,
            Self::golden_carrot => pi::ItemResource::golden_carrot,
            Self::golden_chestplate => pi::ItemResource::golden_chestplate,
            Self::golden_helmet => pi::ItemResource::golden_helmet,
            Self::golden_hoe => pi::ItemResource::golden_hoe,
            Self::golden_horse_armor => pi::ItemResource::golden_horse_armor,
            Self::golden_leggings => pi::ItemResource::golden_leggings,
            Self::golden_pickaxe => pi::ItemResource::golden_pickaxe,
            Self::golden_shovel => pi::ItemResource::golden_shovel,
            Self::golden_sword => pi::ItemResource::golden_sword,
            Self::gray_dye => pi::ItemResource::gray_dye,
            Self::green_dye => pi::ItemResource::green_dye,
            Self::guardian_spawn_egg => pi::ItemResource::guardian_spawn_egg,
            Self::gunpowder => pi::ItemResource::gunpowder,
            Self::heart_of_the_sea => pi::ItemResource::heart_of_the_sea,
            Self::hoglin_spawn_egg => pi::ItemResource::hoglin_spawn_egg,
            Self::honey_bottle => pi::ItemResource::honey_bottle,
            Self::honeycomb => pi::ItemResource::honeycomb,
            Self::hopper_minecart => pi::ItemResource::hopper_minecart,
            Self::horse_spawn_egg => pi::ItemResource::horse_spawn_egg,
            Self::husk_spawn_egg => pi::ItemResource::husk_spawn_egg,
            Self::ink_sac => pi::ItemResource::ink_sac,
            Self::iron_axe => pi::ItemResource::iron_axe,
            Self::iron_boots => pi::ItemResource::iron_boots,
            Self::iron_chestplate => pi::ItemResource::iron_chestplate,
            Self::iron_helmet => pi::ItemResource::iron_helmet,
            Self::iron_hoe => pi::ItemResource::iron_hoe,
            Self::iron_horse_armor => pi::ItemResource::iron_horse_armor,
            Self::iron_ingot => pi::ItemResource::iron_ingot,
            Self::iron_leggings => pi::ItemResource::iron_leggings,
            Self::iron_nugget => pi::ItemResource::iron_nugget,
            Self::iron_pickaxe => pi::ItemResource::iron_pickaxe,
            Self::iron_shovel => pi::ItemResource::iron_shovel,
            Self::iron_sword => pi::ItemResource::iron_sword,
            Self::item_frame => pi::ItemResource::item_frame,
            Self::jungle_boat => pi::ItemResource::jungle_boat,
            Self::knowledge_book => pi::ItemResource::knowledge_book,
            Self::lapis_lazuli => pi::ItemResource::lapis_lazuli,
            Self::lava_bucket => pi::ItemResource::lava_bucket,
            Self::lead => pi::ItemResource::lead,
            Self::leather => pi::ItemResource::leather,
            Self::leather_boots => pi::ItemResource::leather_boots,
            Self::leather_chestplate => pi::ItemResource::leather_chestplate,
            Self::leather_helmet => pi::ItemResource::leather_helmet,
            Self::leather_horse_armor => pi::ItemResource::leather_horse_armor,
            Self::leather_leggings => pi::ItemResource::leather_leggings,
            Self::light_blue_dye => pi::ItemResource::light_blue_dye,
            Self::light_gray_dye => pi::ItemResource::light_gray_dye,
            Self::lime_dye => pi::ItemResource::lime_dye,
            Self::lingering_potion => pi::ItemResource::lingering_potion,
            Self::llama_spawn_egg => pi::ItemResource::llama_spawn_egg,
            Self::magenta_dye => pi::ItemResource::magenta_dye,
            Self::magma_cream => pi::ItemResource::magma_cream,
            Self::magma_cube_spawn_egg => pi::ItemResource::magma_cube_spawn_egg,
            Self::map => pi::ItemResource::map,
            Self::melon_seeds => pi::ItemResource::melon_seeds,
            Self::melon_slice => pi::ItemResource::melon_slice,
            Self::milk_bucket => pi::ItemResource::milk_bucket,
            Self::minecart => pi::ItemResource::minecart,
            Self::mojang_banner_pattern => pi::ItemResource::mojang_banner_pattern,
            Self::mooshroom_spawn_egg => pi::ItemResource::mooshroom_spawn_egg,
            Self::mule_spawn_egg => pi::ItemResource::mule_spawn_egg,
            Self::mushroom_stew => pi::ItemResource::mushroom_stew,
            Self::music_disc_5 => pi::ItemResource::music_disc_5,
            Self::music_disc_11 => pi::ItemResource::music_disc_11,
            Self::music_disc_13 => pi::ItemResource::music_disc_13,
            Self::music_disc_blocks => pi::ItemResource::music_disc_blocks,
            Self::music_disc_cat => pi::ItemResource::music_disc_cat,
            Self::music_disc_chirp => pi::ItemResource::music_disc_chirp,
            Self::music_disc_far => pi::ItemResource::music_disc_far,
            Self::music_disc_mall => pi::ItemResource::music_disc_mall,
            Self::music_disc_mellohi => pi::ItemResource::music_disc_mellohi,
            Self::music_disc_otherside => pi::ItemResource::music_disc_otherside,
            Self::music_disc_pigstep => pi::ItemResource::music_disc_pigstep,
            Self::music_disc_relic => pi::ItemResource::music_disc_relic,
            Self::music_disc_stal => pi::ItemResource::music_disc_stal,
            Self::music_disc_strad => pi::ItemResource::music_disc_strad,
            Self::music_disc_wait => pi::ItemResource::music_disc_wait,
            Self::music_disc_ward => pi::ItemResource::music_disc_ward,
            Self::mutton => pi::ItemResource::mutton,
            Self::name_tag => pi::ItemResource::name_tag,
            Self::nautilus_shell => pi::ItemResource::nautilus_shell,
            Self::nether_brick => pi::ItemResource::nether_brick,
            Self::nether_star => pi::ItemResource::nether_star,
            Self::netherite_axe => pi::ItemResource::netherite_axe,
            Self::netherite_boots => pi::ItemResource::netherite_boots,
            Self::netherite_chestplate => pi::ItemResource::netherite_chestplate,
            Self::netherite_helmet => pi::ItemResource::netherite_helmet,
            Self::netherite_hoe => pi::ItemResource::netherite_hoe,
            Self::netherite_ingot => pi::ItemResource::netherite_ingot,
            Self::netherite_leggings => pi::ItemResource::netherite_leggings,
            Self::netherite_pickaxe => pi::ItemResource::netherite_pickaxe,
            Self::netherite_scrap => pi::ItemResource::netherite_scrap,
            Self::netherite_shovel => pi::ItemResource::netherite_shovel,
            Self::netherite_sword => pi::ItemResource::netherite_sword,
            Self::oak_boat => pi::ItemResource::oak_boat,
            Self::ocelot_spawn_egg => pi::ItemResource::ocelot_spawn_egg,
            Self::orange_dye => pi::ItemResource::orange_dye,
            Self::painting => pi::ItemResource::painting,
            Self::panda_spawn_egg => pi::ItemResource::panda_spawn_egg,
            Self::paper => pi::ItemResource::paper,
            Self::parrot_spawn_egg => pi::ItemResource::parrot_spawn_egg,
            Self::phantom_membrane => pi::ItemResource::phantom_membrane,
            Self::phantom_spawn_egg => pi::ItemResource::phantom_spawn_egg,
            Self::pig_spawn_egg => pi::ItemResource::pig_spawn_egg,
            Self::piglin_brute_spawn_egg => pi::ItemResource::piglin_brute_spawn_egg,
            Self::piglin_spawn_egg => pi::ItemResource::piglin_spawn_egg,
            Self::pillager_spawn_egg => pi::ItemResource::pillager_spawn_egg,
            Self::pink_dye => pi::ItemResource::pink_dye,
            Self::poisonous_potato => pi::ItemResource::poisonous_potato,
            Self::polar_bear_spawn_egg => pi::ItemResource::polar_bear_spawn_egg,
            Self::popped_chorus_fruit => pi::ItemResource::popped_chorus_fruit,
            Self::porkchop => pi::ItemResource::porkchop,
            Self::potato => pi::ItemResource::potato,
            Self::potion => pi::ItemResource::potion,
            Self::powder_snow_bucket => pi::ItemResource::powder_snow_bucket,
            Self::prismarine_crystals => pi::ItemResource::prismarine_crystals,
            Self::prismarine_shard => pi::ItemResource::prismarine_shard,
            Self::pufferfish => pi::ItemResource::pufferfish,
            Self::pufferfish_bucket => pi::ItemResource::pufferfish_bucket,
            Self::pufferfish_spawn_egg => pi::ItemResource::pufferfish_spawn_egg,
            Self::pumpkin_pie => pi::ItemResource::pumpkin_pie,
            Self::pumpkin_seeds => pi::ItemResource::pumpkin_seeds,
            Self::purple_dye => pi::ItemResource::purple_dye,
            Self::quartz => pi::ItemResource::quartz,
            Self::rabbit => pi::ItemResource::rabbit,
            Self::rabbit_foot => pi::ItemResource::rabbit_foot,
            Self::rabbit_hide => pi::ItemResource::rabbit_hide,
            Self::rabbit_spawn_egg => pi::ItemResource::rabbit_spawn_egg,
            Self::rabbit_stew => pi::ItemResource::rabbit_stew,
            Self::ravager_spawn_egg => pi::ItemResource::ravager_spawn_egg,
            Self::raw_copper => pi::ItemResource::raw_copper,
            Self::raw_gold => pi::ItemResource::raw_gold,
            Self::raw_iron => pi::ItemResource::raw_iron,
            Self::red_dye => pi::ItemResource::red_dye,
            Self::redstone => pi::ItemResource::redstone,
            Self::rotten_flesh => pi::ItemResource::rotten_flesh,
            Self::saddle => pi::ItemResource::saddle,
            Self::salmon => pi::ItemResource::salmon,
            Self::salmon_bucket => pi::ItemResource::salmon_bucket,
            Self::salmon_spawn_egg => pi::ItemResource::salmon_spawn_egg,
            Self::scute => pi::ItemResource::scute,
            Self::shears => pi::ItemResource::shears,
            Self::sheep_spawn_egg => pi::ItemResource::sheep_spawn_egg,
            Self::shield => pi::ItemResource::shield,
            Self::shulker_shell => pi::ItemResource::shulker_shell,
            Self::shulker_spawn_egg => pi::ItemResource::shulker_spawn_egg,
            Self::silverfish_spawn_egg => pi::ItemResource::silverfish_spawn_egg,
            Self::skeleton_horse_spawn_egg => pi::ItemResource::skeleton_horse_spawn_egg,
            Self::skeleton_spawn_egg => pi::ItemResource::skeleton_spawn_egg,
            Self::skull_banner_pattern => pi::ItemResource::skull_banner_pattern,
            Self::slime_ball => pi::ItemResource::slime_ball,
            Self::slime_spawn_egg => pi::ItemResource::slime_spawn_egg,
            Self::snowball => pi::ItemResource::snowball,
            Self::spectral_arrow => pi::ItemResource::spectral_arrow,
            Self::spider_eye => pi::ItemResource::spider_eye,
            Self::spider_spawn_egg => pi::ItemResource::spider_spawn_egg,
            Self::splash_potion => pi::ItemResource::splash_potion,
            Self::spruce_boat => pi::ItemResource::spruce_boat,
            Self::spyglass => pi::ItemResource::spyglass,
            Self::squid_spawn_egg => pi::ItemResource::squid_spawn_egg,
            Self::stick => pi::ItemResource::stick,
            Self::stone_axe => pi::ItemResource::stone_axe,
            Self::stone_hoe => pi::ItemResource::stone_hoe,
            Self::stone_pickaxe => pi::ItemResource::stone_pickaxe,
            Self::stone_shovel => pi::ItemResource::stone_shovel,
            Self::stone_sword => pi::ItemResource::stone_sword,
            Self::stray_spawn_egg => pi::ItemResource::stray_spawn_egg,
            Self::strider_spawn_egg => pi::ItemResource::strider_spawn_egg,
            Self::string => pi::ItemResource::string,
            Self::sugar => pi::ItemResource::sugar,
            Self::suspicious_stew => pi::ItemResource::suspicious_stew,
            Self::sweet_berries => pi::ItemResource::sweet_berries,
            Self::tipped_arrow => pi::ItemResource::tipped_arrow,
            Self::tnt_minecart => pi::ItemResource::tnt_minecart,
            Self::totem_of_undying => pi::ItemResource::totem_of_undying,
            Self::trader_llama_spawn_egg => pi::ItemResource::trader_llama_spawn_egg,
            Self::trident => pi::ItemResource::trident,
            Self::tropical_fish => pi::ItemResource::tropical_fish,
            Self::tropical_fish_bucket => pi::ItemResource::tropical_fish_bucket,
            Self::tropical_fish_spawn_egg => pi::ItemResource::tropical_fish_spawn_egg,
            Self::turtle_helmet => pi::ItemResource::turtle_helmet,
            Self::turtle_spawn_egg => pi::ItemResource::turtle_spawn_egg,
            Self::vex_spawn_egg => pi::ItemResource::vex_spawn_egg,
            Self::villager_spawn_egg => pi::ItemResource::villager_spawn_egg,
            Self::vindicator_spawn_egg => pi::ItemResource::vindicator_spawn_egg,
            Self::wandering_trader_spawn_egg => pi::ItemResource::wandering_trader_spawn_egg,
            Self::warped_fungus_on_a_stick => pi::ItemResource::warped_fungus_on_a_stick,
            Self::water_bucket => pi::ItemResource::water_bucket,
            Self::wheat => pi::ItemResource::wheat,
            Self::wheat_seeds => pi::ItemResource::wheat_seeds,
            Self::white_dye => pi::ItemResource::white_dye,
            Self::witch_spawn_egg => pi::ItemResource::witch_spawn_egg,
            Self::wither_skeleton_spawn_egg => pi::ItemResource::wither_skeleton_spawn_egg,
            Self::wolf_spawn_egg => pi::ItemResource::wolf_spawn_egg,
            Self::wooden_axe => pi::ItemResource::wooden_axe,
            Self::wooden_hoe => pi::ItemResource::wooden_hoe,
            Self::wooden_pickaxe => pi::ItemResource::wooden_pickaxe,
            Self::wooden_shovel => pi::ItemResource::wooden_shovel,
            Self::wooden_sword => pi::ItemResource::wooden_sword,
            Self::writable_book => pi::ItemResource::writable_book,
            Self::written_book => pi::ItemResource::written_book,
            Self::yellow_dye => pi::ItemResource::yellow_dye,
            Self::zoglin_spawn_egg => pi::ItemResource::zoglin_spawn_egg,
            Self::zombie_horse_spawn_egg => pi::ItemResource::zombie_horse_spawn_egg,
            Self::zombie_spawn_egg => pi::ItemResource::zombie_spawn_egg,
            Self::zombie_villager_spawn_egg => pi::ItemResource::zombie_villager_spawn_egg,
            Self::zombified_piglin_spawn_egg => pi::ItemResource::zombified_piglin_spawn_egg,
            Self::tadpole_bucket => pi::ItemResource::tadpole_bucket,
            Self::disc_fragment_5 => pi::ItemResource::disc_fragment_5,
            Self::echo_shard => pi::ItemResource::echo_shard,
            Self::goat_horn => pi::ItemResource::goat_horn,
            Self::mangrove_boat => pi::ItemResource::mangrove_boat,
            Self::recovery_compass => pi::ItemResource::recovery_compass,
            Self::allay_spawn_egg => pi::ItemResource::allay_spawn_egg,
            Self::frog_spawn_egg => pi::ItemResource::frog_spawn_egg,
            Self::tadpole_spawn_egg => pi::ItemResource::tadpole_spawn_egg,
            Self::warden_spawn_egg => pi::ItemResource::warden_spawn_egg,
            Self::oak_chest_boat => pi::ItemResource::oak_chest_boat,
            Self::spruce_chest_boat => pi::ItemResource::spruce_chest_boat,
            Self::birch_chest_boat => pi::ItemResource::birch_chest_boat,
            Self::jungle_chest_boat => pi::ItemResource::jungle_chest_boat,
            Self::acacia_chest_boat => pi::ItemResource::acacia_chest_boat,
            Self::dark_oak_chest_boat => pi::ItemResource::dark_oak_chest_boat,
            Self::mangrove_chest_boat => pi::ItemResource::mangrove_chest_boat,
            Self::nether_wart => pi::ItemResource::nether_wart,
            Self::piglin_banner_pattern => pi::ItemResource::piglin_banner_pattern,
            Self::ender_dragon_spawn_egg => pi::ItemResource::ender_dragon_spawn_egg,
            Self::iron_golem_spawn_egg => pi::ItemResource::iron_golem_spawn_egg,
            Self::snow_golem_spawn_egg => pi::ItemResource::snow_golem_spawn_egg,
            Self::wither_spawn_egg => pi::ItemResource::wither_spawn_egg,
            Self::brush => pi::ItemResource::brush,
            Self::pitcher_pod => pi::ItemResource::pitcher_pod,
            Self::angler_pottery_sherd => pi::ItemResource::angler_pottery_sherd,
            Self::archer_pottery_sherd => pi::ItemResource::archer_pottery_sherd,
            Self::arms_up_pottery_sherd => pi::ItemResource::arms_up_pottery_sherd,
            Self::blade_pottery_sherd => pi::ItemResource::blade_pottery_sherd,
            Self::brewer_pottery_sherd => pi::ItemResource::brewer_pottery_sherd,
            Self::burn_pottery_sherd => pi::ItemResource::burn_pottery_sherd,
            Self::danger_pottery_sherd => pi::ItemResource::danger_pottery_sherd,
            Self::explorer_pottery_sherd => pi::ItemResource::explorer_pottery_sherd,
            Self::friend_pottery_sherd => pi::ItemResource::friend_pottery_sherd,
            Self::heart_pottery_sherd => pi::ItemResource::heart_pottery_sherd,
            Self::heartbreak_pottery_sherd => pi::ItemResource::heartbreak_pottery_sherd,
            Self::howl_pottery_sherd => pi::ItemResource::howl_pottery_sherd,
            Self::miner_pottery_sherd => pi::ItemResource::miner_pottery_sherd,
            Self::mourner_pottery_sherd => pi::ItemResource::mourner_pottery_sherd,
            Self::plenty_pottery_sherd => pi::ItemResource::plenty_pottery_sherd,
            Self::prize_pottery_sherd => pi::ItemResource::prize_pottery_sherd,
            Self::sheaf_pottery_sherd => pi::ItemResource::sheaf_pottery_sherd,
            Self::shelter_pottery_sherd => pi::ItemResource::shelter_pottery_sherd,
            Self::skull_pottery_sherd => pi::ItemResource::skull_pottery_sherd,
            Self::snort_pottery_sherd => pi::ItemResource::snort_pottery_sherd,
            Self::netherite_upgrade_smithing_template => {
                pi::ItemResource::netherite_upgrade_smithing_template
            }
            Self::coast_armor_trim_smithing_template => {
                pi::ItemResource::coast_armor_trim_smithing_template
            }
            Self::dune_armor_trim_smithing_template => {
                pi::ItemResource::dune_armor_trim_smithing_template
            }
            Self::eye_armor_trim_smithing_template => {
                pi::ItemResource::eye_armor_trim_smithing_template
            }
            Self::host_armor_trim_smithing_template => {
                pi::ItemResource::host_armor_trim_smithing_template
            }
            Self::raiser_armor_trim_smithing_template => {
                pi::ItemResource::raiser_armor_trim_smithing_template
            }
            Self::rib_armor_trim_smithing_template => {
                pi::ItemResource::rib_armor_trim_smithing_template
            }
            Self::sentry_armor_trim_smithing_template => {
                pi::ItemResource::sentry_armor_trim_smithing_template
            }
            Self::shaper_armor_trim_smithing_template => {
                pi::ItemResource::shaper_armor_trim_smithing_template
            }
            Self::silence_armor_trim_smithing_template => {
                pi::ItemResource::silence_armor_trim_smithing_template
            }
            Self::snout_armor_trim_smithing_template => {
                pi::ItemResource::snout_armor_trim_smithing_template
            }
            Self::spire_armor_trim_smithing_template => {
                pi::ItemResource::spire_armor_trim_smithing_template
            }
            Self::tide_armor_trim_smithing_template => {
                pi::ItemResource::tide_armor_trim_smithing_template
            }
            Self::vex_armor_trim_smithing_template => {
                pi::ItemResource::vex_armor_trim_smithing_template
            }
            Self::ward_armor_trim_smithing_template => {
                pi::ItemResource::ward_armor_trim_smithing_template
            }
            Self::wayfinder_armor_trim_smithing_template => {
                pi::ItemResource::wayfinder_armor_trim_smithing_template
            }
            Self::wild_armor_trim_smithing_template => {
                pi::ItemResource::wild_armor_trim_smithing_template
            }
            Self::camel_spawn_egg => pi::ItemResource::camel_spawn_egg,
            Self::sniffer_spawn_egg => pi::ItemResource::sniffer_spawn_egg,
            Self::torchflower_seeds => pi::ItemResource::torchflower_seeds,
        }
    }
}
